replicaCount: 1

image:
  repository: nginx
  tag: "1.16"

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: "250m"
    memory: "256Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"